version: '3.7'
services:


  redis:
    container_name: workflow_redis
    build:
      context: ./docker/Redis
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"


  backend:
    container_name: workflow_backend
    build:
      context: ./docker/Backend
      dockerfile: Dockerfile
      deploy:
        restart_policy:
          condition: on-failure
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"


  nifi:
    container_name: workflow_nifi
    build:
      context: ./docker/NiFi
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "9090:8080"


  nifi-registry:
    container_name: workflow_nifi-registry
    build:
      context: ./docker/NiFi-Registry
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "19090:18080"